Update CONTRIBUTING.md
puppetlabs/.github pull request #16
Opened 2021-03-25 18:17 UTC by binford2k

The CLA text on puppet.com hasn't gone live yet, but should be shortly.

2021-03-25 18:19 UTC, binford2k commented
Supersedes #14

2021-05-24 10:08 UTC, NicoleS021 requested changes
sq

2021-11-17 01:19 UTC, mwaggett approved these changes

2021-11-17 01:19 UTC, mwaggett commented
Did you want to do any squashing?

2021-12-06 20:25 UTC, merged